<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="56029" started-at="2022-09-21T09:49:22Z" finished-at="2022-09-21T09:50:18Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="56029" started-at="2022-09-21T09:49:22Z" finished-at="2022-09-21T09:50:18Z">
      <class name="org.utilities.TestngRerun">
        <test-method status="PASS" signature="browser()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="browser" is-config="true" duration-ms="4403" started-at="2022-09-21T09:49:22Z" finished-at="2022-09-21T09:49:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="start" is-config="true" duration-ms="13589" started-at="2022-09-21T09:49:26Z" finished-at="2022-09-21T09:49:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="tc2" duration-ms="30" started-at="2022-09-21T09:49:40Z" finished-at="2022-09-21T09:49:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.utilities.TestngRerun.tc2(TestngRerun.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="end" is-config="true" duration-ms="1" started-at="2022-09-21T09:49:40Z" finished-at="2022-09-21T09:49:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="start" is-config="true" duration-ms="5659" started-at="2022-09-21T09:49:40Z" finished-at="2022-09-21T09:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="tc2" duration-ms="2" started-at="2022-09-21T09:49:45Z" finished-at="2022-09-21T09:49:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.utilities.TestngRerun.tc2(TestngRerun.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="end" is-config="true" duration-ms="0" started-at="2022-09-21T09:49:45Z" finished-at="2022-09-21T09:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="start" is-config="true" duration-ms="4859" started-at="2022-09-21T09:49:45Z" finished-at="2022-09-21T09:49:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="tc2()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="tc2" duration-ms="2" started-at="2022-09-21T09:49:50Z" finished-at="2022-09-21T09:49:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.utilities.TestngRerun.tc2(TestngRerun.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="end" is-config="true" duration-ms="1" started-at="2022-09-21T09:49:50Z" finished-at="2022-09-21T09:49:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="start" is-config="true" duration-ms="5283" started-at="2022-09-21T09:49:50Z" finished-at="2022-09-21T09:49:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="tc2()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="tc2" duration-ms="4" started-at="2022-09-21T09:49:55Z" finished-at="2022-09-21T09:49:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[checking expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: checking expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.utilities.TestngRerun.tc2(TestngRerun.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="end" is-config="true" duration-ms="1" started-at="2022-09-21T09:49:55Z" finished-at="2022-09-21T09:49:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="start()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="start" is-config="true" duration-ms="3828" started-at="2022-09-21T09:49:55Z" finished-at="2022-09-21T09:49:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="tc3" duration-ms="17405" started-at="2022-09-21T09:49:59Z" finished-at="2022-09-21T09:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="end()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="end" is-config="true" duration-ms="1" started-at="2022-09-21T09:50:17Z" finished-at="2022-09-21T09:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="browserclose()[pri:0, instance:org.utilities.TestngRerun@5792a0]" name="browserclose" is-config="true" duration-ms="865" started-at="2022-09-21T09:50:17Z" finished-at="2022-09-21T09:50:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserclose -->
      </class> <!-- org.utilities.TestngRerun -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
